# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run:  apk add ruby && gem install mustache
      - name: creates output
        run:  sh ./build.sh
      - name: Pushes to another repository
        id: push_directory
        uses: thanhinterpol/test01@dev
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: output/
          destination-github-username: 'thanhinterpol'
          destination-repository-name: 'test2'
          user-email: thanhinterpol@gmail.com
          commit-message: First commit
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
